apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: fbworkshop.azurecr.io/cluk/demo:1.3
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
